name: ps-ci

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Trust PSGallery
        shell: pwsh
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force -SkipPublisherCheck

      - name: Lint PowerShell scripts
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          if (Test-Path 'scripts') {
            Invoke-ScriptAnalyzer -Path 'scripts' -Recurse -Severity Information,Warning,Error
          } else {
            Write-Host "No scripts folder found; skipping."
          }
