name: ps-ci

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest  # pwsh available; Windows file paths most familiar
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Trust PSGallery
        shell: pwsh
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force -SkipPublisherCheck

      - name: Lint PowerShell scripts
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          if (Test-Path 'scripts') {
            Invoke-ScriptAnalyzer -Path 'scripts' -Recurse -Severity Information,Warning,Error
          } else {
            Write-Host "No scripts folder found; skipping."
          }

      # Optional: quick help check (non-fatal)
      - name: Validate script help (best-effort)
        shell: pwsh
        continue-on-error: true
        run: |
          if (Test-Path 'scripts') {
            Get-ChildItem scripts -Filter *.ps1 -Recurse | ForEach-Object {
              Write-Host "==> $_"
              try { & pwsh -NoProfile -File $_.FullName -? | Out-Null } catch { Write-Host "No help or parameters." }
            }
          }
